theme = "base16-onedark-mg"

[editor]
auto-format = true
bufferline = "always"
color-modes = true
rulers = [80,100]
true-color = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "╎"

[editor.lsp]
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]

[editor.whitespace.characters]
tab = "·"
newline = "¬"
tabpad = "·"

[editor.whitespace.render]
tab = "all"
newline = "all"

[keys.normal]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
